### ISSUE TITLE
Error while setup

### ISSUE THREAD

**Issue by anthonyray** [rickhousley/happn#1]
Hi ! I have an error while I set up : 

```
No local packages or download links found for decouple
error: Could not find suitable distribution for Requirement.parse('decouple')
```

**Comment by rickhousley** [comment]
You need to install the decouple package. Find them here:
https://pypi.python.org/pypi/python-decouple

or do 

> '$ pip install python-decouple'

The decouple package is used to separate the settings file from the actual code base. It's likely that the current settings/tokens are stale and you may have to re-pull them via MITM  with your phone and happn.

I'll fix the dependencies later today.

Best of luck.
