### ISSUE TITLE
Error setting device message

### ISSUE THREAD

**Issue by springjools** [rickhousley/happn#18]
stationary  : WARNING  : unable to change position: Error Setting Device: Header value 342 must be of type str or bytes, not type 'int'

I keep getting those messages, maybe some change in API again. Will try to look into this issue soonish...

**Comment by nateprewitt** [comment]
@springjools this is a change in requests 2.11.0. You simply need to convert your Content-Length headers that are currently ints to strings.

**Comment by mfld-fr** [comment]
Fixed by commit 91849ac64b4bbe59e7a2916c3b6ab2849dd46a2b. Thanks Jools !
