### ISSUE TITLE
WARNING:root:Server denied request for position change: Too Many Requests,

### ISSUE THREAD

**Issue by alexmoreno** [rickhousley/happn#20]
```
WARNING:root:Server denied request for position change: Too Many Requests,
                                will revert to server known location
Traceback (most recent call last):
  File "likeall.py", line 14, in <module>
    myUser = myUser.set_position(20.0477203,-156.5052441) #Hawaii lat/lon
  File "/home/alex/workspace/happn/happn/happn.py", line 155, in set_position
    raise HTTP_MethodError(httpErrors[r.status_code])
happn.happn.HTTP_MethodError: 'Too Many Requests'


```

What am I doing wrong? It is me or the API?

**Comment by pedrocolon93** [comment]
My best guess is that its the api.  You're probably spamming it or the explout might've been covered.

**Comment by alexmoreno** [comment]
If I were spamming I kinda would understand, but this is literally the first time I'm using it.

**Comment by mfld-fr** [comment]
@alexmoreno : Hello, could you please tell us if you already used the official app before running the script, and if you set the device IDs to yours, or reused the default one's from @springjools ?

**Comment by alexmoreno** [comment]
>already used the official app before running the script
Yes.

>if you set the device IDs to yours
No, where? I'm gonna look for it right now. I just set token.

**Comment by mfld-fr** [comment]
Could you please set your IDs in happn/happn/settings.ini ? I wonder if all of us are reusing the same IDs, Happn would complain about too many requests from the same virtual terminal.

**Comment by alexmoreno** [comment]
Do I need to MITM it to get these keys?

**Comment by mfld-fr** [comment]
Yes, as persistent storage on the device by the official app has not been documented yet in this project.

**Comment by mfld-fr** [comment]
No more report from @alexmoreno on that issue, setting own device ID and spacing the position changes are already known issues, so closing that one.
