### ISSUE TITLE
WARNING:root:Server denied request for position change: Gone,

### ISSUE THREAD

**Issue by issamu2k** [rickhousley/happn#21]
> WARNING:root:Server denied request for position change: Gone,
                                will revert to server known location
Traceback (most recent call last):
  File "location.py", line 17, in <module>
    user = user.set_position(20.0477203,-156.5052441)
  File "/home/odroid/Downloads/happn/happn/happn.py", line 155, in set_position
    raise HTTP_MethodError(httpErrors[r.status_code])
happn.happn.HTTP_MethodError: 'Gone'

First time using your code. 
When I run the example code, set_position is failing request with http error code 410 (GONE).
Help.

**Comment by rickhousley** [comment]
You have to supply your own token & id. It is likely that my account (the supplied token and ID) has been blacklisted.

**Comment by rickhousley** [comment]
https://github.com/rickhousley/happn/wiki/Happn-REST-API#facebook-authentication

You may have to use Charles or MITM to get your client-id

**Comment by mfld-fr** [comment]
See also previous issue #20

**Comment by issamu2k** [comment]
Ok, so it took me a while to set everything up.
When you say token & id, it's the GPS_TOKEN and DEVICE_ID, right?
If it is, then I'm stuck. I can't make the app send the set_device command to capture them. Also, if this is sent only on the first login, I can't capture it with charles because login with facebook returns an error every time. Probably because of the certificate. 

This is relevant, the set_position URL is in this format now:
> https://api.happn.fr/api/users/UUUUU/devices/e0f240db-bd16-451d-bdbe-7235df4a32fe

**Comment by mfld-fr** [comment]
@issamu2k : is your terminal rooted, and did you try another MITM like "Packet Capture" ?

**Comment by mfld-fr** [comment]
@issamu2k : yes, we are dealing with the DEVICE_ID (or DID). If you registration was successful on the genuine application, you can read it with a "list of devices" request. See the init() method in the PHP file : https://github.com/rickhousley/happn/blob/master/php/lib/api.php

**Comment by issamu2k** [comment]
I used MITM.
I've figured it out. set_position changed from post to put.

**Comment by mfld-fr** [comment]
@issamu2k : could you please confirm that changing request type from POST to PUT solves the problem you reported ? If confirmed, could you please share the modified code to be merged into mainstream ?

**Comment by springjools** [comment]
I also got this error, of course it's to be expected when you run some very old code and only update the tokens.

However, HTTP 410 Gone indicates that a resource has been moved or deleted. If it would be a blacklisted account or client secret, would we not get something like 403 Forbidden? (Not sure how reliable it is to troubleshoot with the server's http-codes)

**Comment by rickhousley** [comment]
It's likely that happn has changed their API - as Jools mentioned, this is
a fairly old codebase now.

-Rick

**Comment by mfld-fr** [comment]
Fixed in 91849ac64b4bbe59e7a2916c3b6ab2849dd46a2b for the move from POST to PUT. Thanks Jools !
