### ISSUE TITLE
Use Happn app id rather than Tinder one

### ISSUE THREAD

**Issue by mfld-fr** [rickhousley/happn#5]
In README, the proposed link suggests the Tinder application identifier to log on Facebook. I propose to replace the link by (not encoded):

https://www.facebook.com/dialog/oauth?client_id=247294518656661&redirect_uri=fbconnect://success&scope=public_profile&response_type=token

To use the right Happn application identifier and the minimum scope, plus the redirection authorized by the application.

**Comment by rickhousley** [comment]
Great idea. I'll commit this later today.

**Comment by rickhousley** [comment]
The suggested change does not return a token in the address bar.

**Comment by rickhousley** [comment]
Scratch that, it works great.
