### ISSUE TITLE
Changed api?

### ISSUE THREAD

**Issue by springjools** [rickhousley/happn#6]
They must have changed something about their api now, I get a 403 errors when trying to do the oauth.

**Comment by bcaller** [comment]
Yes, the API has changed significantly.

**Comment by mfld-fr** [comment]
@springjools : could you please refine your report and tell us the exact HTTP transaction that fails ?

**Comment by springjools** [comment]
Sure, here is the output:

PS U:\bin\github\happn\examples\creepr> python .\test2.py
```

> --starting test--
> WARNING:root:Server denied request for OAuth token. Status: 403
> Traceback (most recent call last):
>   File ".\test2.py", line 13, in <module>
>     myUser = happn.User(token)
>   File "C:\bin\Python27\lib\site-packages\happn-0.1-py2.7.egg\happn\happn.py", line 108, in __init__
>     self.oauth, self.id = self.get_oauth()
>   File "C:\bin\Python27\lib\site-packages\happn-0.1-py2.7.egg\happn\happn.py", line 274, in get_oauth
>     raise HTTP_MethodError(httpErrors[r.status_code])
> happn.happn.HTTP_MethodError: 'Forbidden'
> --starting test--
> WARNING:root:Server denied request for OAuth token. Status: 403
> Traceback (most recent call last):
>   File ".\test2.py", line 13, in <module>
>     myUser = happn.User(token)
>   File "C:\bin\Python27\lib\site-packages\happn-0.1-py2.7.egg\happn\happn.py", line 108, in __init__
>     self.oauth, self.id = self.get_oauth()
>   File "C:\bin\Python27\lib\site-packages\happn-0.1-py2.7.egg\happn\happn.py", line 274, in get_oauth
>     raise HTTP_MethodError(httpErrors[r.status_code])
> happn.happn.HTTP_MethodError: 'Forbidden'

```

Here is the test script: http://pastebin.com/fXjmKUq8

I redacted the token, but the token is valid and actually the request fails before the validity of the token is checked anyway.

**Comment by mfld-fr** [comment]
You told you redacted the FB token, but how long have you been using that FB token for ? Did you check its expire time in the returned URL from https://www.facebook.com/dialog/oauth ? It is usually quite long but not infinite.

I am asking this question because the remaining of that HTTP POST request to Happn OAuth is constant (client id, client secret, etc), and it worked well yesterday on my side with a CURL command.

**Comment by pedrocolon93** [comment]
Sounds to me like you have an invalid token

**Comment by springjools** [comment]
I checked the token with the debugging tool: https://developers.facebook.com/tools/debug/accesstoken

It's still valid and expires in about a month it says.

The change was yesterday it appears, so if something worked yesterday, it may not work today.

**Comment by rickhousley** [comment]
try getting a new token from the link on this repo.

**Comment by mfld-fr** [comment]
I just tried again now:

First, got a token from FB for the Happn application (USED THE NEW LINK):
https://www.facebook.com/dialog/oauth&client_id=247294518656661&redirect_uri=fbconnect://success&scope=public_profile&response_type=token

Redirected to:
fbconnect://success#access_token=<fb_access_token>&expires_in=5184000

Used the <fb_access_token> to authenticate with Happn:
curl -k -X POST -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -d 'client_id=FUE-idSEP-f7AqCyuMcPr2K-1iCIU_YlvK-M-im3c&client_secret=brGoHSwZsPjJ-lBk0HqEXVtb3UFu-y5l_JcOjD-Ekv&grant_type=assertion&assertion_type=facebook_access_token&assertion=<fb_access_token>&scope=mobile_app'

Got the response:
{"access_token":"<happn_access_token>","expires_in":172800,"scope":"achievement_type_read countries_read language_read locale_read pack_read subscription_type_read report_type_read user_mode_read notification_type_read search_user all_user_read all_image_read user_device_create user_device_read user_device_update user_device_delete user_position_read user_position_update user_notifications_read user_poke_create user_message_create user_message_read user_message_update user_message_delete user_image_create user_image_read user_image_update user_image_delete user_conversation_create user_conversation_read user_conversation_update user_conversation_delete user_order_create user_order_read user_order_update user_applications_read user_applications_update user_applications_delete user_blocked_read user_blocked_create user_blocked_delete user_accepted_read user_accepted_create user_accepted_delete user_rejected_read user_rejected_create user_rejected_delete user_subscription_create user_subscription_read user_subscription_update user_subscription_delete user_achievement_create user_achievement_read user_achievement_update user_achievement_delete user_availability_create user_availability_read user_availability_update user_availability_delete user_social_create user_social_read user_social_update user_social_delete user_update user_delete user_read user_report_read user_report_create user_report_update user_report_delete","user_id":"1881062535","is_new":false,"refresh_token":"<happn_refresh_token>","error_code":0}

I see no behaviour change in the REST API.

Note : <...> are place-holders to hide the actual tokens.

**Comment by mfld-fr** [comment]
I also documented the authentication steps in the Wiki : https://github.com/rickhousley/happn/wiki/Happn-REST-API

**Comment by springjools** [comment]
That's weird. I have been authenticating successfully for a month and it stopped working yesterday. I have made some local modifications to my python installation, like setting it to use utf8 instead of ascii etc. I can log in with my phone so the account works, i tried getting a new access token from the link in the repo and it's still the same response (but now it takes a few seconds before it comes).

I'll try to uninstall the repo and start with a fresh copy, maybe that helps. Or they rolled out some changes only in europe first and not in the US maybe?

**Comment by mfld-fr** [comment]
I operate in France, so in Europe too :-)

**Comment by rickhousley** [comment]
Thank you mfldr-fr. As this issue has not been repeatable this will issue will be closed.

**Comment by springjools** [comment]
Hmmm, sorry to ask again but can you guys actually use the code in python? Is doing the curl request the same thing?

When trying to use the link in the repo, or as posted here by mfld, I get a 500 error and no token as response. I got the access tokens before from:

https://www.facebook.com/dialog/oauth?client_id=247294518656661&redirect_uri=https://www.happn.fr&scope=basic_info,email,public_profile,user_about_me,user_activities,user_birthday,user_education_history,user_friends,user_interests,user_likes,user_location,user_photos,user_relationship_details&response_type=token

and that still works. So was there a typo in the link or what am I doing wrong. The tokens have different scope, is that it?

Also, do I need to modify the app version here to 19.1.0: https://github.com/rickhousley/happn/blob/master/happn/settings.ini#L6

**Comment by mfld-fr** [comment]
First, I think the link you used before to get a FB token is better than the one I put on the Wiki, as you avoid the error message by not redirecting to a local address (as done inside the application with fbconnect://success) but to the main page of the Happn website, that is fortunately allowed by the application registration in Facebook. So let me update the Wiki with the one you use.

Second, the question of the scope is not obvious. I am still trying to identify the minimal scope that allows the API to respond, so requesting only 'basic_info' mandatory scope item, but it is true that the first time I ran the application, I did not restrict the scope and creating my Happn account was successful. I am quite sure I can renew the FB token, but not sure I could create a new & fresh Happn account from another FB account with that minimal scope. Is that your use case ?

About Python : Rick won't be happy to learn that I am not using Python to exercise the API ;-) I took his code as a first reference to understand that API, and I am now exploring it using the CURL command before reusing my findings in PHP. Improving this project documentation is just a way to thank him (and the contributors including you) for the valuable data I found here.

**Comment by rickhousley** [comment]
mfld-fr thank you very much for your contributions. Jools, I'll try to take a look at it this weekend. In the mean time I would suggest using MITM proxy in combination with your phone to look at the traffic and see what token your phone is using. This also may yield some insight as to why this is not working for you.

**Comment by springjools** [comment]
I get a different client id and client secret, and it seems to request the token from https://connect.happn.fr now and not from some url under api.happn.fi: http://imgur.com/ewFoHhU

**Comment by mfld-fr** [comment]
mfld@home ~/happn $ ping connect.happn.fr
PING connect.happn.fr (104.16.92.25) 56(84) bytes of data.
64 bytes from 104.16.92.25: icmp_seq=1 ttl=53 time=12.2 ms

mfld@home ~/happn $ ping api.happn.fr
PING api.happn.fr (104.16.92.25) 56(84) bytes of data.
64 bytes from 104.16.92.25: icmp_seq=1 ttl=53 time=12.2 ms

Both DN point to the same IP address, so no impact at the end, but it is a finding to keep in mind when updating the code.

For client credentials, could you please tell us the exact version of your Happn application ? Mine is 19.1.0.

**Comment by springjools** [comment]
Hmm, I only see this: User-Agent: happn/838 CFNetwork/609.1.4 Darwin/13.0.0

It's the user-agent field in the request header. It's an iPhone with ios 6.8.3 so it could be an old version of happn.

**Comment by springjools** [comment]
Ok, sorry for posting that old info, I so that was from version 13.0.0, but it apparently still works.

I tested with the curl command you provided and got the same response:

PS U:\bin\github\userTools> curl -k -X POST -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -d 'client_id=FUE-idSEP-f7AqCyuMcPr2K-1iCIU_YlvK -M-im3c&client_secret=brGoHSwZsPjJ-lBk0HqEXVtb3UFu-y5l_JcOjD-Ekv&grant_type=assertion&assertion_type=facebook_access_token&assertion=xxxxx&scope=mobile_app' https://api.happn.fr/connect/oauth/token {"access_token":"yyyyy","expires_in":172800,"scope":"achievement_type_read countries_read language_read locale_read pack_read subsc ription_type_read report_type_read user_mode_read notification_type_read search_user all_user_read all_image_read user_device_create user_device_read user_devic e_update user_device_delete user_position_read user_position_update user_notifications_read user_poke_create user_message_create user_message_read user_message_ update user_message_delete user_image_create user_image_read user_image_update user_image_delete user_conversation_create user_conversation_read user_conversati on_update user_conversation_delete user_order_create user_order_read user_order_update user_applications_read user_applications_update user_applications_delete user_blocked_read user_blocked_create user_blocked_delete user_accepted_read user_accepted_create user_accepted_delete user_rejected_read user_rejected_create u ser_rejected_delete user_subscription_create user_subscription_read user_subscription_update user_subscription_delete user_achievement_create user_achievement_r ead user_achievement_update user_achievement_delete user_availability_create user_availability_read user_availability_update user_availability_delete user_socia l_create user_social_read user_social_update user_social_delete user_update user_delete user_read user_report_read user_report_create user_report_update user_re port_delete","user_id":"uid","is_new":false,"refresh_token":"zzzzz","error_code":0}

But it does not work in python, so could it then be something related with the ssl and the requests library? There was a similar issue here: 
https://github.com/skipperbent/happn-php-sdk/issues/1

**Comment by mfld-fr** [comment]
Well... if it works on your side with CURL, and on mine with CURL and PHP (both based on OpenSSL on my Linux distro), it looks like either something got wrong in Rick's Python code, or you broke something else in your local configuration. And I am afraid I cannot help in both cases.

The only way I could see to help you would be to share my PHP code.

**Comment by springjools** [comment]
Yeah I guess we will eventually find out the reason. Thanks for helping by the way.

But I also tested it in POSTMAN (there is a function to import a curl command), and then I again get the 403 error. Maybe this piece of info will help?

http://i.imgur.com/8qJdqnzm.png

**Comment by springjools** [comment]
I can work around the issue by adding a "verify=False" parameter to the requests command. That disables the verification of the SSL certificate so it produces a lot of nag text, but it works. Maybe one solution could be to change to use pycurl instead, or maybe there is a simple way.

**Comment by mfld-fr** [comment]
I also disable the certificate verification since the beginning of my experiment : option -k for CURL, or curl_setopt ($c, CURLOPT_SSL_VERIFYPEER, FALSE) in my PHP code.

**Comment by springjools** [comment]
Actually I found that the certificate error happened because I was monitoring the network with charles proxy. With some additional testing I finally found the culprit: the user-agent field. It works if I change the user-agent from "Dalvik/1.6.0 (Linux; U; Android 4.4.2; SCH-I535 Build/KOT49H)" to something else, like "Mozilla/5.0".

**Comment by mfld-fr** [comment]
OK, so let me record in the Wiki that one should use the following header to avoid this issue:
```
User-Agent: Happn/19.1.0 AndroidSDK/19
```

**Comment by rickhousley** [comment]
Jools feel free to submit a pull request with this modification
