### ISSUE TITLE
API changes in 19.1.0

### ISSUE THREAD

**Issue by mfld-fr** [rickhousley/happn#7]
After a new MITM session, I noticed the following changes in the REST API:
1- A new header after device creation : X-Happn-DID: device_id
2- A new step with FB token confirmation after authentication : POST /api/auth/proof
3- A modified URL to update the location : PUT /api/users/user_id/devices/device_id

Maybe a code update ?

**Comment by rickhousley** [comment]
Definitely in need of a new update. Unfortunately I don't have a lot of time on my hands, but over this summer I'm looking to re-write the api with proper unit testing and expanded features. I'm very willing to accept contributions!

**Comment by mfld-fr** [comment]
I would be glad to contribute to your project, but I am afraid my goal is not exactly the same beyond documenting the Happn REST API.

There are many ones on GitHub related to Happn hacking, but only a few are starred and remain active after their first rushes from scratch. This one and SkipperBent's are in the top, but:

* You use Python, and it looks like you are targeting a client application, while I am targeting a web application, so PHP,

* SkipperBent reuses its own "Pecee" framework, that IMHO brings very little value in querying a REST API, as I can replace all his stuff by a single class "Rest" with a single method.

Therefore, in their current states, these projects do not match mine... until you would allow to create a PHP implementation in parallel of the current Python one in the same "reverse engineering" project.

What is your opinion about this ?

**Comment by rickhousley** [comment]
PHP is definitely not my forte. However, utilizing this with Flask (simple python webserver) could definitely be interesting.

**Comment by mfld-fr** [comment]
Well... that is very clear, and I must admit, consistent :-) Let me do the "less worst choice" then... so let me join SkipperBent's project, as we share the common point to use PHP.

Nevertheless, I would be happy to continue sharing knowledge of the REST API with this one, through participating to the discussion.

**Comment by rickhousley** [comment]
I wasn't very sure of what you were asking. Would you like to contribute as part of this project just on the PHP front? I'd be totally open to that (provided you don't remove the python stuff).

**Comment by mfld-fr** [comment]
Yes, that's it : the idea is to provide both Python and PHP implementations in the same project, to ease the information sharing about the Happn REST API. I already have some PHP stuff that could be a starting point, and I could move from https://github.com/mfld-fr/happn-php repository to this one.

**Comment by rickhousley** [comment]
Welcome.

**Comment by mfld-fr** [comment]
Thank you very much for this open mindset !

I just moved the stuff to a new `php` branch and a sub-folder with the same name, to let you review and decide whether you merge in master or not.

**Comment by mfld-fr** [comment]
As this issue diverged from its initial topic, I created a new one (issue #11) to focus back on the API update, and I am closing this one.
